# -*- coding: utf-8 -*-
"""Task 1 SDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p3LkMhmhM5BwPjhcbOo8tNby-W_ZUPBI
"""

#import the library
import folium
from folium.plugins import MarkerCluster
import pandas as pd
import requests
import json
import pprint
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import descartes
!pip install googletrans
from googletrans import Translator
import copy

#download the data ubike
response = requests.get("http://odws.hccg.gov.tw/001/Upload/25/OpenData/9059/59/67e94b18-b8ba-4c6a-9a2a-e66638a31895.json")
content = response.content
json_tree = json.loads(content)
#pprint.pprint(json_tree)

#simple pre processing
df = pd.DataFrame(json_tree)
translator = Translator()
for col in df.columns:
    df.rename(columns={col:translator.translate(col).text},inplace=True)
df['latitude'] = df['latitude'].astype(float) #convert string to float
df['longitude'] = df['longitude'].astype(float) #convert string to float
for i in range(0, 63):
  df['Site name'][i] = translator.translate(df['Site name'][i]).text

#Define coordinates of where we want to center our map
hsinchu_coords = [24.8138, 120.9675]
#Create the map
my_map = folium.Map(location = hsinchu_coords, zoom_start = 13)
#put the marker
for i in range(0, 63):
  folium.Marker([df['latitude'][i], df['longitude'][i]], popup = "Site name: " + df['Site name'][i]). add_to(my_map)
my_map