# -*- coding: utf-8 -*-
"""wordcloud_abstract_covid19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ju3othpfsZt9PmnjS5Uh3jaM3yCwz9kt
"""

# Import library
import pandas as pd
import numpy as np
from wordcloud import WordCloud, ImageColorGenerator
from PIL import Image
from numpy import random
import matplotlib.pyplot as plt

# Function for coloring word into black and white
def grey_color_func(word, font_size, position, orientation, random_state=None,
                    **kwargs):
    return "hsl(0, 0%%, %d%%)" % random.randint(60, 100)

# Import data abstract after preprocessing
df = pd.read_csv('abstract_clean.csv')
df.columns = ['abstract']
text = list(df.abstract)
text = str(text)

# Import mask/shape
covid_mask = np.array(Image.open('covid19.png'))
image_colors = ImageColorGenerator(covid_mask)

# Create wordcloud model
word_cloud = WordCloud(width=covid_mask.shape[1], height=covid_mask.shape[0],
                      background_color='black',
                      min_font_size=14,
                      mask=covid_mask, max_words = 1000,
                       margin=5, random_state=1).generate(text)
# Plot the wordcloud
plt.figure(figsize=(15,15))
plt.imshow(word_cloud.recolor(color_func=grey_color_func, random_state=3), 
           interpolation='bilinear') 
word_cloud.to_file('wc_covid19.png') # Save the wordcloud
plt.axis("off") 
plt.tight_layout(pad = 0) 
plt.show()